plugins { id 'com.android.application' }

android {
    namespace 'com.convoy.offline'
    compileSdk 35

    defaultConfig {
        applicationId 'com.convoy.offline'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '0.4.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    androidResources { noCompress 'pmtiles', 'graph', 'db', 'pbf' }
    buildTypes { release { minifyEnabled false } }
}

dependencies {
    implementation 'org.maplibre.gl:android-sdk-opengl:13.5.2'
}
