package com.convoy.offline;

import android.Manifest;import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.*;import android.view.*;import android.widget.*;import java.io.*;import java.security.SecureRandom;import java.util.*;

public class MainActivity extends Activity {
 private static final int BG=0xFF101923,CARD=0xFF1B2A36,GREEN=0xFF73E5BE,TEXT=0xFFF0F5F6,MUTED=0xFF9CB0BC;
 private LinearLayout root,body,mapPanel,crewPanel;private RichMap map;private DrivingInstruments instruments;private TextView status,detail,gps,voice,crewSummary,navPrimary,navSecondary,routeSummary;private Button trip,ptt,vox;private final Handler handler=new Handler(Looper.getMainLooper());private int tab=0;private Runnable permissionAction;private boolean importing=false;private boolean hadTrip=false;
 private int dp(float n){return (int)(getResources().getDisplayMetrics().density*n+0.5f);} 
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextColor(color);t.setTextSize(size);t.setPadding(0,dp(3),0,dp(3));return t;}
 private Button button(String label,boolean primary){Button b=new Button(this);b.setText(label);b.setTextSize(13);b.setAllCaps(false);b.setTextColor(primary?BG:TEXT);b.setBackground(shape(primary?GREEN:CARD,14));b.setMinHeight(dp(48));b.setMinimumWidth(0);b.setPadding(dp(12),dp(6),dp(12),dp(6));return b;}
 private void spaced(LinearLayout parent,View child,int height){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,height<0?height:dp(height));p.bottomMargin=dp(10);parent.addView(child,p);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();}
 private void build(){root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setPadding(dp(14),dp(9),dp(14),dp(9));setContentView(root);
 root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets bars;if(Build.VERSION.SDK_INT>=30){bars=in.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(14),bars.top+dp(7),dp(14),bars.bottom+dp(7));}return in;});
 LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout branding=new LinearLayout(this);branding.setOrientation(1);TextView title=text("convoy",32,TEXT);title.setTypeface(Typeface.create("sans-serif-medium",0));branding.addView(title);branding.addView(text("STAY CLOSE. GO FURTHER.",9,GREEN));head.addView(branding,new LinearLayout.LayoutParams(0,-2,1));trip=button("Start trip",true);head.addView(trip);trip.setOnClickListener(v->{if(ConvoyService.current!=null)new AlertDialog.Builder(this).setTitle("End this trip?").setMessage("Location sharing and voice will stop on this phone.").setNegativeButton("Keep going",null).setPositiveButton("End trip",(d,w)->stopService(new Intent(this,ConvoyService.class))).show();else setup();});spaced(root,head,-2);
 status=text("Your next adventure, connected",17,TEXT);status.setTypeface(null,Typeface.BOLD);root.addView(status);detail=text("No mobile signal needed. Set up together before driving.",12,MUTED);detail.setMaxLines(3);spaced(root,detail,-2);
 LinearLayout tabs=new LinearLayout(this);for(String label:new String[]{"Map","Plan","Crew","Guide"}){final int i=tabs.getChildCount();Button btab=button(label,false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(42),1);lp.setMargins(0,0,dp(5),0);tabs.addView(btab,lp);btab.setOnClickListener(v->{tab=i;renderTab();});}spaced(root,tabs,42);
 body=new LinearLayout(this);body.setOrientation(1);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));map=new RichMap(this);map.setWaypoints(TripPlan.load(this));map.setNavigationMode(true);map.setOnPlaceSelectedListener(this::placeSheet);mapPanel=new LinearLayout(this);mapPanel.setOrientation(1);
 LinearLayout tools=new LinearLayout(this);Button search=button("Search",false),importMap=button("Map pack",false),mode=button("Drive",false),center=button("GPS",false),minus=button("-",false),plus=button("+",false);tools.addView(search,new LinearLayout.LayoutParams(0,dp(40),1));tools.addView(importMap,new LinearLayout.LayoutParams(0,dp(40),1));tools.addView(mode,new LinearLayout.LayoutParams(dp(56),dp(40)));tools.addView(center,new LinearLayout.LayoutParams(dp(48),dp(40)));tools.addView(minus,new LinearLayout.LayoutParams(dp(36),dp(40)));tools.addView(plus,new LinearLayout.LayoutParams(dp(36),dp(40)));spaced(mapPanel,tools,40);search.setOnClickListener(v->searchPlaces());importMap.setOnClickListener(v->chooseMap());mode.setOnClickListener(v->{map.setNavigationMode(!map.isNavigationMode());mode.setText(map.isNavigationMode()?"Drive":"North");map.recenter();});center.setOnClickListener(v->map.recenter());minus.setOnClickListener(v->map.changeZoom(-1));plus.setOnClickListener(v->map.changeZoom(1));
 LinearLayout quick=new LinearLayout(this);String[][] quickItems={{"Fuel","fuel"},{"Coffee","cafe"},{"Food","restaurant"},{"Parking","parking"},{"Shops","supermarket"},{"EV","charging_station"}};for(String[] q:quickItems){Button bq=button(q[0],false);LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(0,dp(36),1);qp.setMargins(0,0,dp(4),0);quick.addView(bq,qp);String term=q[1];bq.setTextSize(11);bq.setOnClickListener(v->map.searchCategory(term,this::showSearchResults));}spaced(mapPanel,quick,36);
 FrameLayout mapFrame=new FrameLayout(this);mapFrame.setBackground(shape(0xFF15232B,16));mapFrame.addView(map,new FrameLayout.LayoutParams(-1,-1));LinearLayout banner=new LinearLayout(this);banner.setOrientation(LinearLayout.VERTICAL);banner.setPadding(dp(12),dp(5),dp(12),dp(5));banner.setBackground(shape(0xE6006E4A,13));navPrimary=text("OFFLINE MAP • ready",10,0xFFE9FFF5);navPrimary.setTypeface(null,Typeface.BOLD);navPrimary.setSingleLine(true);navSecondary=text("Tap a place for details",14,0xFFFFFFFF);navSecondary.setTypeface(null,Typeface.BOLD);navSecondary.setSingleLine(true);banner.addView(navPrimary);banner.addView(navSecondary);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,dp(56));bp.gravity=Gravity.TOP;bp.setMargins(dp(7),dp(7),dp(116),0);mapFrame.addView(banner,bp);instruments=new DrivingInstruments(this);FrameLayout.LayoutParams ip=new FrameLayout.LayoutParams(dp(108),dp(250));ip.gravity=Gravity.TOP|Gravity.RIGHT;ip.setMargins(0,dp(68),dp(6),0);mapFrame.addView(instruments,ip);routeSummary=text("Offline vector map • roads + places + POIs",11,0xFFE8F1F4);routeSummary.setGravity(Gravity.CENTER_VERTICAL);routeSummary.setPadding(dp(10),0,dp(10),0);routeSummary.setBackground(shape(0xD9101923,10));FrameLayout.LayoutParams rp=new FrameLayout.LayoutParams(-1,dp(34));rp.gravity=Gravity.BOTTOM;rp.setMargins(dp(7),0,dp(7),dp(7));mapFrame.addView(routeSummary,rp);mapPanel.addView(mapFrame,new LinearLayout.LayoutParams(-1,0,1));gps=text("GPS starts when you begin a trip",10,MUTED);gps.setSingleLine(true);mapPanel.addView(gps);crewSummary=text("No crew connected",10,GREEN);crewSummary.setSingleLine(true);mapPanel.addView(crewSummary);
 voice=text("Offline voice • half duplex",13,GREEN);voice.setGravity(Gravity.CENTER);spaced(root,voice,-2);
 LinearLayout audio=new LinearLayout(this);ptt=button("Hold to talk",true);vox=button("Hands-free off",false);LinearLayout.LayoutParams a=new LinearLayout.LayoutParams(0,dp(58),1);a.setMargins(0,0,dp(8),0);audio.addView(ptt,a);audio.addView(vox,new LinearLayout.LayoutParams(0,dp(58),1));spaced(root,audio,58);
 ptt.setOnTouchListener((v,event)->{ConvoyService s=ConvoyService.current;if(s==null)return false;switch(event.getActionMasked()){case MotionEvent.ACTION_DOWN:s.ptt=true;ptt.setText("Release to listen");return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:s.ptt=false;ptt.setText("Hold to talk");v.performClick();return true;default:return true;}});
 vox.setOnClickListener(v->{ConvoyService s=ConvoyService.current;if(s==null){setup();return;}if(s.vox){s.vox=false;return;}new AlertDialog.Builder(this).setTitle("Hands-free voice").setMessage("The microphone transmits when it detects loud speech. Road noise can trigger it. One person speaks at a time; received speech temporarily pauses your microphone transmission.\n\nUse the phone or car audio at a moderate volume. Set this up while parked, then test with a passenger. Headset microphones and car Bluetooth routing vary by device.").setNegativeButton("Cancel",null).setPositiveButton("Enable",(d,w)->s.vox=true).show();});renderTab();}
 private void renderTab(){
  body.removeAllViews();
  if(tab==0){body.addView(mapPanel,new LinearLayout.LayoutParams(-1,-1));return;}
  ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(0,dp(8),0,dp(10));scroll.addView(box);body.addView(scroll,new LinearLayout.LayoutParams(-1,-1));
  if(tab==1){crewPanel=null;renderPlan(box);return;}
  if(tab==2){crewPanel=box;updateCrew();return;}
  crewPanel=null;
  addSection(box,"Before you leave","Install the same APK on every phone. Allow precise Location, Microphone and Nearby devices. Turn Location and your selected radio on. Everyone uses the same group key.");
  addSection(box,"Trip plan & POIs","Use Plan to save fuel, food, rest, viewpoint, meet-up, hazard and custom stops. Planned stops are stored on this phone and appear on the map. The dashed line only joins stops in order; it is not road routing. Share a plan before departure and paste/import it on the other phones.");
  addSection(box,"Wi-Fi • recommended","Choose one host. It can create a local hotspot with no internet. Friends join the displayed Wi-Fi in Android settings, choose Join in Convoy, and enter the host’s local IP. Keep the no-internet Wi-Fi connection when Android asks. A passenger can also use a portable router or a manually enabled hotspot.");
  addSection(box,"Bluetooth • alternative","Pair each friend’s phone with the host in Android Bluetooth settings first. Host starts Bluetooth mode; friends choose that paired host and enter the group key. Wi-Fi and Bluetooth modes are separate; there is no automatic radio switching.");
  addSection(box,"Offline vector maps","Convoy 0.4 uses MapLibre with local PMTiles. The bundled Shrewsbury pack includes vector roads, buildings, land use, place labels and POIs. You can import another compatible .pmtiles region without mobile data. Tap mapped places for details, or use Search for the local place index.");
  addSection(box,"While moving","Let a passenger handle the screen. Enable hands-free before departure; hold-to-talk is for passengers or when parked. Voice is walkie-talkie style, one speaker at a time. Adjust media volume for received voice. Radio range can be short inside moving cars; stay within the connection’s tested range.");
  addSection(box,"Know what is live","Markers become stale after 15 seconds without a fresh GPS fix. Crew cards show age, accuracy and heartbeat. Convoy now calculates car routes fully offline inside the installed routing region; outside that region it will clearly say routing is unavailable. This is not emergency equipment.");
  addSection(box,"Privacy & stopping","No account, server, analytics or location history. Group traffic is encrypted with a shared key: only give it to your friends. Every group member can hear and see the group. Voice is not recorded to files. End trip in the app or notification to stop the service. Android may still stop it under power restrictions; test screen-off behaviour on your phones.");
  addSection(box,"Map information",map.mapName+"\n"+map.attribution+"\n\nConvoy 0.4.0 • vector-navigation build");
 }
 private void addSection(LinearLayout box,String title,String value){TextView h=text(title,17,TEXT);h.setTypeface(null,Typeface.BOLD);box.addView(h);TextView t=text(value,14,MUTED);t.setLineSpacing(dp(3),1);spaced(box,t,-2);}
 private void updateCrew(){if(tab!=2||crewPanel==null)return;crewPanel.removeAllViews();ConvoyService s=ConvoyService.current;if(s==null){addSection(crewPanel,"Your crew appears here","Start or join a trip to share positions.");return;}addSection(crewPanel,s.myName+" • you",(s.host?"Host":"Member")+" · "+(s.bluetooth?"Bluetooth":"Wi-Fi")+" · "+s.connectionCount()+" direct link(s)");
 if(s.host&&!s.bluetooth){addSection(crewPanel,"Wi-Fi details",(s.hotspotInfo.isEmpty()?"Using existing Wi-Fi / hotspot":s.hotspotInfo)+"\n\nHost IP addresses:\n"+s.addresses()+"\n\nUse the address belonging to the hotspot / Wi-Fi interface.");}
 ArrayList<ConvoyService.Member> list=new ArrayList<>(s.members.values());list.sort(Comparator.comparing(m->m.name));for(ConvoyService.Member m:list){long seen=Math.max(0,(SystemClock.elapsedRealtime()-m.received)/1000);String line=(seen<=10?"Link recently heard":"Link not heard")+" · "+seen+"s ago\n";if(m.located){line+=(m.age()>15000?"STALE GPS":"Fresh GPS")+" · "+m.age()/1000+"s old · ±"+Math.round(m.accuracy)+" m\n"+String.format(Locale.US,"%.5f, %.5f",m.lat,m.lon);if(s.fix!=null){float[] distance=new float[1];android.location.Location.distanceBetween(s.fix.getLatitude(),s.fix.getLongitude(),m.lat,m.lon,distance);line+="\nLast-position distance: "+(distance[0]<1000?Math.round(distance[0])+" m":String.format(Locale.US,"%.1f km",distance[0]/1000));}}else line+="Waiting for this phone's GPS fix";addSection(crewPanel,m.name,line);}
 if(list.isEmpty())addSection(crewPanel,"Waiting for friends","Keep the app open on each phone while connecting.");Button mute=button(s.muted?"Unmute received voice":"Mute received voice",false);crewPanel.addView(mute);mute.setOnClickListener(v->s.muted=!s.muted);}
 private final Runnable tick=new Runnable(){public void run(){ConvoyService s=ConvoyService.current;boolean running=s!=null&&s.active;if(running){hadTrip=true;getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);trip.setText("End trip");status.setText(s.status);detail.setText(s.detail.isEmpty()?"Group ready • share your key privately":s.detail);voice.setText(s.muted?"Received voice muted":s.voiceStatus());vox.setText(s.vox?"Hands-free on":"Hands-free off");if(s.fix==null)gps.setText("GPS • waiting for satellites / Location enabled");else{long age=(SystemClock.elapsedRealtimeNanos()-s.fix.getElapsedRealtimeNanos())/1000000;gps.setText((age>15000?"STALE GPS":"GPS fix")+" · ±"+Math.round(s.fix.getAccuracy())+" m · "+age/1000+"s old");}long fresh=s.members.values().stream().filter(m->m.age()<=15000).count();crewSummary.setText(s.connectionCount()+" radio link(s) · "+fresh+" fresh crew position(s)");}else{getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);trip.setText("Start trip");status.setText(hadTrip?"Trip ended":"Your next adventure, connected");detail.setText("No mobile signal needed. Set up together before driving.");voice.setText("Offline voice • half duplex");gps.setText("GPS starts when you begin a trip");crewSummary.setText("No crew connected");vox.setText("Hands-free off");}ptt.setEnabled(running&&s.connectionCount()>0);updateNavigationBanner();map.refresh();updateCrew();handler.postDelayed(this,1000);}};
 private void updateNavigationBanner(){
  if(navPrimary==null||navSecondary==null||routeSummary==null)return;
  String target=map.getTargetName(),instruction=map.getInstruction();float metres=map.getDistanceRemaining();int eta=map.getEtaSeconds();
  if(target==null||target.isEmpty()){navPrimary.setText("EXPLORE • roads + places offline");navSecondary.setText("Tap a place or add a stop in Plan");routeSummary.setText("Offline vector map • search places • tap POIs");return;}
  if(instruction==null||instruction.isEmpty()){instruction=map.routingReady()?"Calculating offline route…":"Preparing offline routing…";}
  if(metres>=0){navPrimary.setText(formatMiles(metres)+(eta>0?" • "+formatEta(eta):"")+" • "+target);routeSummary.setText((eta>0?"ETA "+clockEta(eta)+" • ":"")+formatMiles(metres)+" • "+target);}
  else{navPrimary.setText("OFFLINE ROUTE • "+target);routeSummary.setText(target+" • "+instruction);}
  navSecondary.setText(instruction);
 }
 private String formatMiles(float metres){if(metres<161)return Math.max(10,Math.round(metres/10f)*10)+" m";if(metres<1609)return Math.round(metres*1.09361f)+" yd";return String.format(Locale.UK,"%.1f mi",metres/1609.344f);}
 private String formatEta(int seconds){int m=Math.max(1,(int)Math.ceil(seconds/60.0));return m<60?m+" min":(m/60)+" h "+(m%60)+" min";}
 private String clockEta(int seconds){Calendar c=Calendar.getInstance();c.add(Calendar.SECOND,seconds);return String.format(Locale.UK,"%02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE));}
 @Override protected void onStart(){super.onStart();map.onStart();}
 @Override protected void onResume(){super.onResume();map.onResume();handler.post(tick);}
 @Override protected void onPause(){handler.removeCallbacks(tick);ConvoyService s=ConvoyService.current;if(s!=null)s.ptt=false;map.onPause();super.onPause();}
 @Override protected void onStop(){map.onStop();super.onStop();}
 @Override public void onLowMemory(){super.onLowMemory();map.onLowMemory();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);map.onSaveInstanceState(out);}
 @Override protected void onDestroy(){handler.removeCallbacks(tick);map.dispose();super.onDestroy();}
 private EditText field(LinearLayout box,String label,String value,boolean secret){box.addView(text(label,12,MUTED));EditText e=new EditText(this);e.setTextColor(TEXT);e.setSingleLine(true);e.setText(value);e.setTextSize(16);if(secret)e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);box.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));return e;}
 private String randomKey(){byte[] b=new byte[8];new SecureRandom().nextBytes(b);StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x));return s.toString();}
 private void setup(){ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(22),dp(12),dp(22),dp(8));scroll.addView(box);EditText name=field(box,"Your name (max 32 characters)",getPreferences(0).getString("name",""),false);box.addView(text("Your car icon",12,MUTED));Spinner car=new Spinner(this);String[] carNames={"MX-5 NC PRHT","Toyota GT86","Skyline R34","Supra Mk4","Honda NSX","Impreza GC8","Lancer Evo VI","AE86 Trueno","350Z","MX-5 NA","Generic car"};String[] carKeys={"nc","gt86","r34","supra","nsx","gc8","evo6","ae86","z350","na","generic"};car.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,carNames));String savedCar=getPreferences(0).getString("car","nc");for(int ci=0;ci<carKeys.length;ci++)if(carKeys[ci].equals(savedCar))car.setSelection(ci);box.addView(car);Spinner role=new Spinner(this);role.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Host a convoy","Join a convoy"}));box.addView(role);Spinner transport=new Spinner(this);transport.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Wi-Fi hotspot / local network","Paired Bluetooth"}));box.addView(transport);EditText key=field(box,"Group key • everyone must enter exactly the same key",randomKey(),true);box.addView(text("Keep the generated key when hosting. Replace it with your host’s key when joining.",12,MUTED));EditText ip=field(box,"Host IPv4 address • needed only to join Wi-Fi",getPreferences(0).getString("ip",""),false);ip.setHint("e.g. 192.168.43.1");ip.setHintTextColor(MUTED);CheckBox hotspot=new CheckBox(this);hotspot.setText("Create a local Wi-Fi hotspot when hosting");hotspot.setTextColor(TEXT);hotspot.setChecked(true);box.addView(hotspot);box.addView(text("Set up while parked. This build needs real-device range and audio testing before a remote trip.",12,MUTED));
 AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Bring your crew together").setView(scroll).setNegativeButton("Cancel",null).setPositiveButton("Continue",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String n=name.getText().toString().trim(),k=key.getText().toString(),addr=ip.getText().toString().trim();boolean hosting=role.getSelectedItemPosition()==0,bt=transport.getSelectedItemPosition()==1;String chosenCar=carKeys[car.getSelectedItemPosition()];if(n.isEmpty()||n.length()>32){name.setError("Enter 1–32 characters");return;}if(k.length()<12||k.length()>128){key.setError("Use a key of 12–128 characters");return;}if(!hosting&&!bt&&!validIp(addr)){ip.setError("Enter the host’s IPv4 address from its Crew tab");return;}getPreferences(0).edit().putString("name",n).putString("ip",addr).putString("car",chosenCar).apply();Runnable begin=()->{if(bt&&!hosting)pickBluetooth(n,k,chosenCar);else launch(n,k,hosting,bt,addr,hotspot.isChecked(),chosenCar);};dialog.dismiss();permissions(bt,hosting&&!bt&&hotspot.isChecked(),begin);}));dialog.show();}
 private boolean validIp(String value){String[] a=value.split("\\.");if(a.length!=4)return false;try{for(String x:a){int n=Integer.parseInt(x);if(n<0||n>255)return false;}return true;}catch(Exception e){return false;}}
 private void permissions(boolean bt,boolean hotspot,Runnable action){ArrayList<String> needed=new ArrayList<>(Arrays.asList(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.RECORD_AUDIO));if(Build.VERSION.SDK_INT>=31&&bt)needed.add(Manifest.permission.BLUETOOTH_CONNECT);if(Build.VERSION.SDK_INT>=33){if(hotspot)needed.add(Manifest.permission.NEARBY_WIFI_DEVICES);needed.add(Manifest.permission.POST_NOTIFICATIONS);}ArrayList<String> missing=new ArrayList<>();for(String p:needed)if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)missing.add(p);if(missing.isEmpty())action.run();else{permissionAction=action;requestPermissions(missing.toArray(new String[0]),5);}}
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] grants){super.onRequestPermissionsResult(code,permissions,grants);if(code==5){boolean ok=true;for(int i=0;i<permissions.length;i++)if(!permissions[i].equals(Manifest.permission.POST_NOTIFICATIONS)&&grants[i]!=PackageManager.PERMISSION_GRANTED)ok=false;Runnable action=permissionAction;permissionAction=null;if(ok&&action!=null)action.run();else new AlertDialog.Builder(this).setTitle("Permissions needed").setMessage("Convoy needs precise Location, Microphone, and the permissions for your selected connection. Enable them in Android app settings, then start the trip again.").setPositiveButton("App settings",(d,w)->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton("Close",null).show();}}
 private void pickBluetooth(String name,String key,String car){try{BluetoothAdapter a=getSystemService(BluetoothManager.class).getAdapter();if(a==null||!a.isEnabled())throw new IOException("Turn on Bluetooth and pair with the host in Android settings first.");ArrayList<BluetoothDevice> devices=new ArrayList<>(a.getBondedDevices());if(devices.isEmpty())throw new IOException("No paired devices. Pair with the host in Android Bluetooth settings first.");String[] labels=new String[devices.size()];for(int i=0;i<devices.size();i++)labels[i]=devices.get(i).getName()+"\n"+devices.get(i).getAddress();new AlertDialog.Builder(this).setTitle("Choose your paired host phone").setItems(labels,(d,w)->launch(name,key,false,true,devices.get(w).getAddress(),false,car)).setNegativeButton("Cancel",null).show();}catch(Exception e){alert(e.getMessage());}}
 private void launch(String name,String key,boolean host,boolean bt,String address,boolean hotspot,String car){try{Intent i=new Intent(this,ConvoyService.class).putExtra("name",name).putExtra("key",key).putExtra("host",host).putExtra("bluetooth",bt).putExtra("address",address).putExtra("hotspot",hotspot).putExtra("car",car);startForegroundService(i);tab=host&&!bt?2:0;renderTab();}catch(Exception e){alert(e.getMessage());}}
 private void renderPlan(LinearLayout box){
  ArrayList<TripPlan.Waypoint> points=TripPlan.load(this);map.setWaypoints(points);
  addSection(box,"Plan the day","Save the places your convoy may need even when mobile data disappears. The order below is the stop order shown on the map. Share the plan before leaving so each phone has a local copy.");
  LinearLayout actions=new LinearLayout(this);Button add=button("+ Add stop",true),paste=button("Paste plan",false);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(48),1);ap.setMargins(0,0,dp(7),0);actions.addView(add,ap);actions.addView(paste,new LinearLayout.LayoutParams(0,dp(48),1));spaced(box,actions,48);
  LinearLayout actions2=new LinearLayout(this);Button share=button("Share plan",false),clear=button("Clear",false);LinearLayout.LayoutParams ap2=new LinearLayout.LayoutParams(0,dp(44),1);ap2.setMargins(0,0,dp(7),0);actions2.addView(share,ap2);actions2.addView(clear,new LinearLayout.LayoutParams(0,dp(44),1));spaced(box,actions2,44);
  add.setOnClickListener(v->waypointDialog(null));paste.setOnClickListener(v->pastePlan());share.setOnClickListener(v->sharePlan());clear.setOnClickListener(v->{if(points.isEmpty())return;new AlertDialog.Builder(this).setTitle("Clear trip plan?").setMessage("This removes all saved stops from this phone.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{TripPlan.save(this,new ArrayList<TripPlan.Waypoint>());refreshPlan();renderTab();}).show();});
  if(points.isEmpty()){addSection(box,"No stops yet","Add a fuel stop, food/rest break, viewpoint, meet-up/rejoin point, hazard or any custom POI. If a live GPS fix is available it will be pre-filled when you add a stop.");return;}
  int index=1;for(TripPlan.Waypoint w:points){final TripPlan.Waypoint point=w;LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(13),dp(10),dp(13),dp(10));card.setBackground(shape(CARD,14));TextView h=text(index+"  "+TripPlan.symbol(w.type)+" "+w.name,16,w.done?MUTED:TEXT);h.setTypeface(null,Typeface.BOLD);card.addView(h);String meta=w.type+(w.done?" • visited":" • planned")+"\n"+String.format(Locale.US,"%.5f, %.5f",w.lat,w.lon);ConvoyService service=ConvoyService.current;if(service!=null&&service.fix!=null){float[] out=new float[1];android.location.Location.distanceBetween(service.fix.getLatitude(),service.fix.getLongitude(),w.lat,w.lon,out);meta+="\nFrom your last fix: "+formatDistance(out[0]);}card.addView(text(meta,12,MUTED));LinearLayout row=new LinearLayout(this);Button show=button("Show",false),done=button(w.done?"Undo":"Done",false),edit=button("Edit",false),del=button("×",false);for(Button b:new Button[]{show,done,edit,del}){LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(42),1);bp.setMargins(0,dp(7),dp(5),0);row.addView(b,bp);}card.addView(row);show.setOnClickListener(v->{map.focus(point.lat,point.lon);tab=0;renderTab();});done.setOnClickListener(v->{point.done=!point.done;TripPlan.upsert(this,point);refreshPlan();renderTab();});edit.setOnClickListener(v->waypointDialog(point));del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete "+point.name+"?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,x)->{TripPlan.remove(this,point.id);refreshPlan();renderTab();}).show());spaced(box,card,-2);index++;}
  addSection(box,"Map behaviour","Convoy routes to the next unvisited stop over the bundled offline road graph. The thin dashed line still shows the overall stop sequence; the thick blue line is the calculated driving route.");
 }
 private String formatDistance(float metres){return metres<1000?Math.round(metres)+" m":String.format(Locale.US,"%.1f km",metres/1000f);}
 private void refreshPlan(){map.setWaypoints(TripPlan.load(this));map.refresh();}
 private void waypointDialog(TripPlan.Waypoint existing){
  LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(22),dp(8),dp(22),0);String[] types={"Fuel","Food","Rest","Viewpoint","Meet-up","Hazard","Other"};Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,types));box.addView(text("Type",12,MUTED));box.addView(type);if(existing!=null){for(int i=0;i<types.length;i++)if(types[i].equals(existing.type))type.setSelection(i);}
  EditText name=field(box,"Name",existing==null?"":existing.name,false);double lat0=Double.NaN,lon0=Double.NaN;if(existing!=null){lat0=existing.lat;lon0=existing.lon;}else{ConvoyService service=ConvoyService.current;if(service!=null&&service.fix!=null){lat0=service.fix.getLatitude();lon0=service.fix.getLongitude();}}
  EditText lat=field(box,"Latitude",Double.isNaN(lat0)?"":String.format(Locale.US,"%.6f",lat0),false),lon=field(box,"Longitude",Double.isNaN(lon0)?"":String.format(Locale.US,"%.6f",lon0),false);int numberType=android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED;lat.setInputType(numberType);lon.setInputType(numberType);box.addView(text("Current GPS coordinates are pre-filled when Convoy has a fix. You can also enter coordinates manually while planning at home.",12,MUTED));
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(existing==null?"Add planned stop":"Edit planned stop").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty()){name.setError("Enter a name");return;}try{double la=Double.parseDouble(lat.getText().toString().trim()),lo=Double.parseDouble(lon.getText().toString().trim());if(la< -90||la>90||lo< -180||lo>180)throw new NumberFormatException();String t=(String)type.getSelectedItem();TripPlan.Waypoint w=existing==null?TripPlan.create(n,t,la,lo):new TripPlan.Waypoint(existing.id,n,t,la,lo,existing.created,existing.done);TripPlan.upsert(this,w);refreshPlan();dialog.dismiss();renderTab();}catch(Exception e){lat.setError("Check latitude / longitude");lon.setError("Check latitude / longitude");}}));dialog.show();
 }
 private void sharePlan(){ArrayList<TripPlan.Waypoint> points=TripPlan.load(this);if(points.isEmpty()){alert("Add at least one planned stop first.");return;}Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_SUBJECT,"Convoy trip plan");send.putExtra(Intent.EXTRA_TEXT,TripPlan.encode(points));startActivity(Intent.createChooser(send,"Share Convoy plan"));}
 private void pastePlan(){
  EditText input=new EditText(this);input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setHint("Paste CONVOY_PLAN_V1 text here");input.setMinLines(8);input.setGravity(Gravity.TOP);input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);input.setPadding(dp(14),dp(10),dp(14),dp(10));try{ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null&&cm.hasPrimaryClip()&&cm.getPrimaryClip()!=null&&cm.getPrimaryClip().getItemCount()>0){CharSequence c=cm.getPrimaryClip().getItemAt(0).coerceToText(this);if(c!=null&&c.toString().contains(TripPlan.HEADER))input.setText(c);}}catch(Exception ignored){}
  FrameLayout wrap=new FrameLayout(this);wrap.setPadding(dp(18),0,dp(18),0);wrap.addView(input,new FrameLayout.LayoutParams(-1,dp(260)));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Import shared trip plan").setMessage("This replaces the plan saved on this phone.").setView(wrap).setNegativeButton("Cancel",null).setPositiveButton("Import",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{ArrayList<TripPlan.Waypoint> points=TripPlan.decode(input.getText().toString());if(points.isEmpty()){input.setError("No valid Convoy stops found");return;}TripPlan.save(this,points);refreshPlan();dialog.dismiss();renderTab();Toast.makeText(this,points.size()+" stops imported",Toast.LENGTH_LONG).show();}));dialog.show();
 }
 private void chooseMap(){if(importing){alert("A map is already being imported.");return;}new AlertDialog.Builder(this).setTitle("Offline vector map pack").setMessage("Convoy already includes a rich Shrewsbury vector map with roads, buildings, place names and POIs.\n\nYou can replace the basemap with another Protomaps-compatible PMTiles (.pmtiles) file. The bundled Shrewsbury place-search and routing data remain tied to the Shrewsbury region in this build.").setNegativeButton("Cancel",null).setPositiveButton("Choose PMTiles",(d,w)->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,9);}).show();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=9||result!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;importing=true;Toast.makeText(this,"Importing vector map…",Toast.LENGTH_LONG).show();new Thread(()->{File tmp=new File(getFilesDir(),"region-import.pmtiles");try{String title="Imported vector region";try(android.database.Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())title=c.getString(0);}try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("Could not read that file");byte[] buffer=new byte[65536];long total=0;int n;while((n=in.read(buffer))!=-1){total+=n;if(total>2L*1024*1024*1024)throw new IOException("Use a map pack smaller than 2 GB");out.write(buffer,0,n);}}validatePmtiles(tmp);String finalTitle=title;runOnUiThread(()->{try{File target=new File(getFilesDir(),"region.pmtiles");if(target.exists()&&!target.delete())throw new IOException("Could not replace the old map");if(!tmp.renameTo(target))throw new IOException("Could not install the map pack");getSharedPreferences("convoy",0).edit().putString("mapName",finalTitle).apply();map.load();map.recenter();Toast.makeText(this,"Vector map ready",Toast.LENGTH_LONG).show();}catch(Exception e){alert(e.getMessage());}finally{importing=false;}});}catch(Exception e){tmp.delete();runOnUiThread(()->{importing=false;alert("Map import failed: "+e.getMessage());});}},"map-import").start();}
 private void validatePmtiles(File file)throws IOException{try(InputStream in=new BufferedInputStream(new FileInputStream(file))){byte[] h=new byte[7];if(in.read(h)!=7||!"PMTiles".equals(new String(h,java.nio.charset.StandardCharsets.US_ASCII)))throw new IOException("That file is not a PMTiles archive");}}
 private void searchPlaces(){final EditText q=new EditText(this);q.setSingleLine(true);q.setTextColor(TEXT);q.setHintTextColor(MUTED);q.setHint("fuel, cafe, supermarket, castle…");q.setPadding(dp(14),0,dp(14),0);AlertDialog d=new AlertDialog.Builder(this).setTitle("Search offline places").setMessage("Search the Shrewsbury place index stored on this phone.").setView(q).setNegativeButton("Cancel",null).setPositiveButton("Search",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String s=q.getText().toString().trim();if(s.length()<2){q.setError("Type at least two characters");return;}d.dismiss();map.search(s,this::showSearchResults);}));d.show();}
 private void showSearchResults(ArrayList<PlaceInfo> places){if(places==null||places.isEmpty()){alert("No matching places were found in the offline Shrewsbury index.");return;}String[] labels=new String[places.size()];for(int i=0;i<places.size();i++){PlaceInfo p=places.get(i);String sub=p.subtitle();labels[i]=p.name+(sub.isEmpty()?"":"\n"+sub);}new AlertDialog.Builder(this).setTitle("Offline places").setItems(labels,(d,w)->{PlaceInfo p=places.get(w);map.focus(p.lat,p.lon);placeSheet(p);}).setNegativeButton("Close",null).show();}
 private void placeSheet(PlaceInfo p){if(p==null)return;StringBuilder b=new StringBuilder();if(p.category!=null&&!p.category.isEmpty())b.append(p.category.replace('_',' '));ConvoyService svc=ConvoyService.current;if(svc!=null&&svc.fix!=null){float[] d=new float[1];android.location.Location.distanceBetween(svc.fix.getLatitude(),svc.fix.getLongitude(),p.lat,p.lon,d);b.append(b.length()>0?" • ":"").append(formatDistance(d[0])).append(" away");}if(p.address!=null&&!p.address.isEmpty())b.append(b.length()>0?"\n":"").append(p.address);if(p.brand!=null&&!p.brand.isEmpty()&&!p.brand.equalsIgnoreCase(p.name))b.append("\nBrand: ").append(p.brand);if(p.cuisine!=null&&!p.cuisine.isEmpty())b.append("\nCuisine: ").append(p.cuisine.replace(';',','));if(p.operator!=null&&!p.operator.isEmpty())b.append("\nOperator: ").append(p.operator);if(p.openingHours!=null&&!p.openingHours.isEmpty())b.append("\nHours: ").append(p.openingHours);if(p.wheelchair!=null&&!p.wheelchair.isEmpty())b.append("\nWheelchair: ").append(p.wheelchair);if(p.internetAccess!=null&&!p.internetAccess.isEmpty())b.append("\nInternet: ").append(p.internetAccess);if(p.phone!=null&&!p.phone.isEmpty())b.append("\nPhone: ").append(p.phone);if(p.website!=null&&!p.website.isEmpty())b.append("\nWeb: ").append(p.website);if(p.source!=null&&!p.source.isEmpty())b.append("\n\nData: ").append(p.source);String[] items={"Navigate here","Add as stop","Meet here","Show on map"};new AlertDialog.Builder(this).setTitle(p.name).setMessage(b.length()==0?String.format(Locale.UK,"%.5f, %.5f",p.lat,p.lon):b.toString()).setItems(items,(d,w)->{if(w==0){map.navigateTo(p);tab=0;renderTab();}else if(w==1||w==2){TripPlan.Waypoint x=TripPlan.create(p.name,w==2?"Meet-up":placeType(p.category),p.lat,p.lon);TripPlan.upsert(this,x);refreshPlan();Toast.makeText(this,"Added to trip plan",Toast.LENGTH_SHORT).show();if(w==2){map.clearManualTarget();}}else{map.focus(p.lat,p.lon);tab=0;renderTab();}}).setNegativeButton("Close",null).show();}
 private String placeType(String category){String c=category==null?"":category.toLowerCase(Locale.ROOT);if(c.contains("fuel")||c.contains("charging"))return "Fuel";if(c.contains("restaurant")||c.contains("cafe")||c.contains("food")||c.contains("pub"))return "Food";if(c.contains("view")||c.contains("attraction")||c.contains("museum")||c.contains("castle"))return "Viewpoint";if(c.contains("parking")||c.contains("toilet")||c.contains("hotel")||c.contains("camp"))return "Rest";return "Other";}
 private void alert(String message){if(!isFinishing()&&!isDestroyed())new AlertDialog.Builder(this).setTitle("Convoy").setMessage(message).setPositiveButton("OK",null).show();}
}
